default_platform(:ios)

platform :ios do
end

desc 'Runs unit tests'
lane :test do
    clear_derived_data

    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"

    begin
        scan(
            device: "iPhone 8 (14.5)",
            code_coverage: true,
            disable_concurrent_testing: true,
            fail_build: true,
            skip_slack: true,
            prelaunch_simulator: true,
            xcargs: "-UseNewBuildSystem=YES",
            cloned_source_packages_path: "SourcePackages"
        )
    rescue => ex
        UI.important("Tests failed for #{ex}")
    end
end
