disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - anyobject_protocol
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - discouraged_direct_init
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_string
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_length
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - implicit_return
  - implicitly_unwrapped_optional
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - nimble_operator
  - no_fallthrough_only
  - notification_center_detachment
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - object_literal
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - statement_position
  - strict_fileprivate
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - toggle_bool
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - type_body_length
  - type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate
  - xctfail_message
  - yoda_condition
operator_usage_whitespace:
  severity: error
syntactic_sugar: error
trailing_comma:
  severity: error
trailing_newline: error
trailing_semicolon: error
unused_closure_parameter: error
unused_optional_binding:
  severity: error
vertical_whitespace:
  severity: error
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true
cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: false
file_length:
  warning: 400
  error: 500
function_body_length:
  warning: 50
  error: 60
function_parameter_count:
  warning: 5
  error: 6
large_tuple:
  warning: 2
  error: 3
line_length:
  warning: 150
  error: 180
  ignores_urls: false
  ignores_function_declarations: false
  ignores_comments: true
nesting:
  type_level: 2
type_name:
  excluded:
    - ID
  max_length:
    warning: 50
    error: 60
identifier_name:
  excluded:
    - id
    - or
    - in 
    - ok
    - x
    - y
    - z
force_unwrapping:
  severity: error
custom_rules:
  asset_prohibited:
    included: '.*\.swift'
    name: 'Use Images or Colors instead of Asset'
    regex: ' Asset\.'
    message: 'Incorrect enum'
    severity: error
        
included:
  - ${SRCROOT}
  - ${SRCROOT}/../Sources
  - ${SRCROOT}/../../Sources
excluded:
  - ${SRCROOT}/Carthage
  - ${SRCROOT}/.build
  - ${SRCROOT}/Playgrounds
  - ${SRCROOT}/Submodules
  - ${SRCROOT}/SourcePackages
  - ${SRCROOT}/*/SourcePackages
  - ${SRCROOT}/*/*/SourcePackages
  - ${SRCROOT}/*/*/*/SourcePackages
  - ${SRCROOT}/Vendor
  - ${SRCROOT}/Pods
  - ${SRCROOT}/bundle
  - ${SRCROOT}/*Tests
  - ${SRCROOT}/*UITests
  - ${SRCROOT}/Tests
